# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build VarC Font

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip freeze

    - name: Build fonts
      run: |
        ./buildFont.sh

    - name: Storing font artifacts
      uses: actions/upload-artifact@master
      with:
        name: font_files
        path: variable_ttf

    - name: Storing UFO artifacts
      uses: actions/upload-artifact@master
      with:
        name: figArnaud.ufo
        path: figArnaud.ufo

    - name: Storing .designspace
      uses: actions/upload-artifact@master
      with:
        name: figArnaud.designspace
        path: figArnaud.designspace
