name: Build VarC Font

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # allow manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build fonts
      run: |
        ./buildFont.sh

    - name: Storing font artifacts
      uses: actions/upload-artifact@master
      with:
        name: font_files
        path: variable_ttf
